In [1]:
#Import necessay libraries
import numpy
import math

In [2]:
# cost function
def costfunc(x,y):
  ''' This is the problem we will be
  optimizing, each chromosome of parent has a cost
  which is calculated from this cost function'''
  
  return (3*(1-x)**2 * math.exp(-(x**2)-(y+1)**2))- (10*(x/5-x**3-y**5)*math.exp(-x**2-y**2))-(1/3*math.exp(-(x+1)**2-y**2))

In [3]:
# Parameter initialization 
genes = 2
chromosomes = 10
mattingPoolSize = 6
offspringSize = chromosomes - mattingPoolSize
lb = -5
ub = 5
populationSize = (chromosomes, genes)
generations = 3



#Population initialization
population = numpy.random.uniform(lb, ub, populationSize)
for generation in range(generations):
  print(("Generation:", generation+1))
  fitness =[costfunc(i[0],i[1]) for i in population ]
  print("\npopulation")
  print(population)
  print("\nfitness calcuation")
  print(fitness)

  

  # Following statement will create an empty two dimensional array to store parents
  parents = numpy.empty((mattingPoolSize, population.shape[1]))
  # A loop to extract one parent in each iteration
  for p in range(mattingPoolSize):
    #print(p)
    # Finding index of fittest chromosome in the population
    fittestIndex = numpy.where(fitness == numpy.max(fitness))
    # Extracting index of fittest chromosome
    fittestIndex = fittestIndex[0][0]
    # Copying fittest chromosome into parents array
    parents[p, :] = population[fittestIndex, :]
    # Changing fitness of fittest chromosome to avoid reselection of that chromosome 
    fitness[fittestIndex] = -1
  print("\nParents:")
  print(parents)

  # Following statement will create an empty two dimensional array to store offspring
  offspring = numpy.empty((offspringSize, population.shape[1]))
  for k in range(offspringSize):
    #Determining the crossover point 
    crossoverPoint = numpy.random.randint(0,genes)
    #print(crossoverPoint)
    # Index of the first parent.
    #print(k)
    parent1Index = k%parents.shape[0]
    #print(parent1Index)
    # Index of the second.
    parent2Index = (k+1)%parents.shape[0]
    #print(parent2Index)
    # Extracting first half of the offspring
    offspring[k, 0: crossoverPoint] = parents[parent1Index, 0: crossoverPoint]
    #print(offspring)
    # Extracting second half of the offspring
    offspring[k, crossoverPoint:] = parents[parent2Index, crossoverPoint:]
  print("\nOffspring after crossover:")
  print(offspring)

  # Implementation of random initialization mutation. 
  for index in range(offspring.shape[0]):
    randomIndex = numpy.random.randint(1,genes)
    randomValue = numpy.random.uniform(lb, ub, 1)
    #print(randomValue)
    offspring [index, randomIndex] = offspring [index, randomIndex] + randomValue
    #print(offspring)
  print("\n Offspring after Mutation")
  print(offspring)
  
  population[0:parents.shape[0], :] = parents
  population[parents.shape[0]:, :] = offspring
  print("\nNew Population for next generation:")
  print(population)
  


fitness =[costfunc(i[0],i[1]) for i in population ]
fittestIndex = numpy.where(fitness == numpy.max(fitness))
# Extracting index of fittest chromosome
fittestIndex = fittestIndex[0][0]
# Getting Best chromosome
fittestInd = population[fittestIndex, :]
bestFitness = fitness[fittestIndex]
print("\nBest Individual:")
print(fittestInd)
print("\nBest Individual's Fitness:")
print(bestFitness)





('Generation:', 1)

population
[[ 4.66587676 -2.03590824]
 [ 0.3999946   1.21821955]
 [ 4.31953838  4.39810811]
 [-4.43191766 -1.60625834]
 [ 3.50896791 -3.97112223]
 [-0.09699708  3.09616838]
 [ 4.80734345  3.82993186]
 [ 2.22749432 -3.79869822]
 [-2.70442771  3.34882937]
 [ 0.37245891 -3.19020186]]

fitness calcuation
[8.48944023648213e-09, 5.14866581497319, 5.406547753448587e-13, -2.294098473214097e-07, 6.427422088198212e-09, 0.19354569170607214, 3.6581043340872696e-13, -1.7000105222044978e-05, 3.58367310721073e-05, -0.10088081221395391]

Parents:
[[ 0.3999946   1.21821955]
 [-0.09699708  3.09616838]
 [-2.70442771  3.34882937]
 [ 4.66587676 -2.03590824]
 [ 3.50896791 -3.97112223]
 [ 4.31953838  4.39810811]]

Offspring after crossover:
[[-0.09699708  3.09616838]
 [-0.09699708  3.34882937]
 [-2.70442771 -2.03590824]
 [ 4.66587676 -3.97112223]]

 Offspring after Mutation
[[-0.09699708  7.95881234]
 [-0.09699708  7.13291825]
 [-2.70442771 -1.76908752]
 [ 4.66587676 -1.09290292]]

New Po